name: devcon-node
services:
  devcon-node:
    image: devcon-node:1.20
    container_name: devcon-node
    hostname: devcon-node
    init: true
    tty: true
    user: node
    working_dir: /home/node/workspace
    networks:
      devcon-node-net:
    volumes:
      - workspace-data:/home/node/workspace
      - vscode-server-extensions:/home/node/.vscode-server/extensions
      - type: bind
        source: ${SHARE_DIR:-./workspace_share}
        target: /share
    environment:
      ENV LANGUAGE: ja_JP.UTF-8
      ENV LANG: ja_JP.UTF-8
      ENV LC_ALL: ja_JP.UTF-8
      EDITOR: code
      NPM_CONFIG_USERCONFIG: ${NPM_CONFIG_USERCONFIG:-/home/node/.npmrc}
      DH_SHARE_DIR: ${SHARE_DIR:-./workspace_share}

volumes:
  workspace-data:
    name: devcon-node-node-workspace-data
  vscode-server-extensions:
    name: devcon-node-vscode-server-extensions

networks:
  devcon-node-net:
    name: devcon-node-net